# Generated by Django 3.2.dev20210102203948 on 2021-02-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
