# Generated by Django 3.2.dev20210102203948 on 2021-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picblog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
