# Generated by Django 2.2.5 on 2021-03-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picblog', '0004_post_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
